/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : stoplight.sm
 */


extern int YellowTimer;
extern int NSGreenTimer;
extern int EWGreenTimer;


#include "stoplight.h"
#include "stoplight_sm.h"

#define getOwner(fsm) (fsm)->_owner

static void smc_ex4_StoplightState_Timeout(struct smc_ex4_stoplightContext *const fsm)
{
    getState(fsm)->Default(fsm);
}

static void smc_ex4_StoplightState_Default(struct smc_ex4_stoplightContext *const fsm)
{
    State_Default(fsm);
}

#define smc_ex4_StopMap_EastWestGreen_Default smc_ex4_StoplightState_Default
#define smc_ex4_StopMap_EastWestYellow_Default smc_ex4_StoplightState_Default
#define smc_ex4_StopMap_NorthSouthGreen_Default smc_ex4_StoplightState_Default
#define smc_ex4_StopMap_NorthSouthYellow_Default smc_ex4_StoplightState_Default
#define smc_ex4_StopMap_DefaultState_Timeout smc_ex4_StoplightState_Timeout
static void smc_ex4_StopMap_EastWestGreen_Timeout(struct smc_ex4_stoplightContext *const fsm)
{
    struct smc_ex4_Stoplight *ctxt = getOwner(fsm);

    clearState(fsm);
    smc_ex4_Stoplight_TurnLight(ctxt, EWLIGHT, YELLOW);
    smc_ex4_Stoplight_SetTimer(ctxt, YellowTimer);
    setState(fsm, &smc_ex4_StopMap_EastWestYellow);

}

const struct smc_ex4_StoplightState smc_ex4_StopMap_EastWestGreen = {
    smc_ex4_StopMap_EastWestGreen_Timeout,
    smc_ex4_StopMap_EastWestGreen_Default,
    0
};
static void smc_ex4_StopMap_EastWestYellow_Timeout(struct smc_ex4_stoplightContext *const fsm)
{
    struct smc_ex4_Stoplight *ctxt = getOwner(fsm);

    clearState(fsm);
    smc_ex4_Stoplight_TurnLight(ctxt, EWLIGHT, RED);
    smc_ex4_Stoplight_TurnLight(ctxt, NSLIGHT, GREEN);
    smc_ex4_Stoplight_SetTimer(ctxt, NSGreenTimer);
    setState(fsm, &smc_ex4_StopMap_NorthSouthGreen);

}

const struct smc_ex4_StoplightState smc_ex4_StopMap_EastWestYellow = {
    smc_ex4_StopMap_EastWestYellow_Timeout,
    smc_ex4_StopMap_EastWestYellow_Default,
    1
};
static void smc_ex4_StopMap_NorthSouthGreen_Timeout(struct smc_ex4_stoplightContext *const fsm)
{
    struct smc_ex4_Stoplight *ctxt = getOwner(fsm);

    clearState(fsm);
    smc_ex4_Stoplight_TurnLight(ctxt, NSLIGHT, YELLOW);
    smc_ex4_Stoplight_SetTimer(ctxt, YellowTimer);
    setState(fsm, &smc_ex4_StopMap_NorthSouthYellow);

}

const struct smc_ex4_StoplightState smc_ex4_StopMap_NorthSouthGreen = {
    smc_ex4_StopMap_NorthSouthGreen_Timeout,
    smc_ex4_StopMap_NorthSouthGreen_Default,
    2
};
static void smc_ex4_StopMap_NorthSouthYellow_Timeout(struct smc_ex4_stoplightContext *const fsm)
{
    struct smc_ex4_Stoplight *ctxt = getOwner(fsm);

    clearState(fsm);
    smc_ex4_Stoplight_TurnLight(ctxt, NSLIGHT, RED);
    smc_ex4_Stoplight_TurnLight(ctxt, EWLIGHT, GREEN);
    smc_ex4_Stoplight_SetTimer(ctxt, EWGreenTimer);
    setState(fsm, &smc_ex4_StopMap_EastWestGreen);

}

const struct smc_ex4_StoplightState smc_ex4_StopMap_NorthSouthYellow = {
    smc_ex4_StopMap_NorthSouthYellow_Timeout,
    smc_ex4_StopMap_NorthSouthYellow_Default,
    3
};

#ifdef NO_STOPLIGHT_SM_MACRO
void smc_ex4_stoplightContext_Init(struct smc_ex4_stoplightContext *const fsm, struct smc_ex4_Stoplight *const owner)
{
    FSM_INIT(fsm, &smc_ex4_StopMap_NorthSouthGreen);
    fsm->_owner = owner;
}

void smc_ex4_stoplightContext_Timeout(struct smc_ex4_stoplightContext *const fsm)
{
    const struct smc_ex4_StoplightState* state = getState(fsm);

    assert(state != NULL);
    setTransition(fsm, "Timeout");
    state->Timeout(fsm);
    setTransition(fsm, NULL);
}
#endif

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
